# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proxy.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'proxy.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import chat_pb2 as chat__pb2
import heartbeat_pb2 as heartbeat__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bproxy.proto\x12\x04\x63hat\x1a\nchat.proto\x1a\x0fheartbeat.proto2\xd4\x01\n\x0cProxyService\x12-\n\x04Join\x12\x11.chat.JoinRequest\x1a\x12.chat.JoinResponse\x12)\n\x0bSendMessage\x12\r.chat.Message\x1a\x0b.chat.Empty\x12/\n\x0fReceiveMessages\x12\x0b.chat.Empty\x1a\r.chat.Message0\x01\x12\x39\n\x0cSwitchServer\x12\x13.chat.SwitchRequest\x1a\x14.chat.SwitchResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proxy_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PROXYSERVICE']._serialized_start=51
  _globals['_PROXYSERVICE']._serialized_end=263
# @@protoc_insertion_point(module_scope)
